Implemented all arrays tasks
juliaakor/js-assignments pull request #4
Opened 2023-08-21 11:37 UTC by juliaakor

## Changes
- Added implementation of all functions
- Added comments of possible other implementation (not for all functions)

### Implemented Functions
1. findElement
2. generateOdds
3. doubleArray
4. getArrayOfPositives
5. getArrayOfStrings
6. removeFalsyValues
7. getUpperCaseStrings
8. getStringsLength
9. insertItem
10. getHead
11. getTail
12. toCsvText
13. toStringList
14. toArrayOfSquares
15. getMovingSum
16. getSecondItems
17. propagateItemsByPositionIndex
18. get3TopItems
19. getPositivesCount
20. sortDigitNamesByNumericOrder
21. getItemsSum
22. getFalsyValuesCount
23. findAllOccurences
24. sortCitiesArray
25. getIdentityMatrix
26. getIntervalArray
27. distinct
28. group
29. selectMany
30. getElementByIndexes
31. swapHeadAndTail

### Notes
During implementation, some functions can be implemented in several ways, so comments with possible other implementations are also added

2023-08-21 15:23 UTC, paperstick requested changes

2023-08-21 15:23 UTC, paperstick commented on task/04-arrays-tasks.js
> +      : 0
What would be the output of the function if we just return `arr.filter(value => value > 0 && typeof value === 'number').length `?

2023-08-21 15:23 UTC, paperstick commented on task/04-arrays-tasks.js
> +      const numbersOrder = ['zero', 'one', 'two', 'three', 'four','five', 'six', 'seven', 'eight', 'nine']
It would be much better to move this constant out of the function, because we are currently create the same array on every iteration. Also, it would be better to use an object in this case, since the time complexity of `indexOf` method is `O(n)`, while accessing the value by key in an object is `O(1)`

2023-08-21 15:23 UTC, paperstick commented on task/04-arrays-tasks.js
> +   , 0)
Can you come up with a more cleaner solution using `filter` method?

2023-08-21 15:23 UTC, paperstick commented on task/04-arrays-tasks.js
> +      }
Try to avoid using nested ternary operators since it results in a more messy code, which always hard to read.

Actually, in this task, everything can be simplified with the help of `localCompare` method

2023-08-21 15:23 UTC, paperstick commented on task/04-arrays-tasks.js
> +   return Array.from({length: end - start + 1},(value, index)=> start + index)
```suggestion
   return Array.from({ length: end - start + 1 }, (_, index) => start + index)
```

Don't forget about the consistency in spaces, it also gives a bit cleaner look to the code.
And, in such cases, where we need only the second argument of the arrow function, we can declare the first one as `_` (underscore)

2023-08-22 08:30 UTC, juliaakor commented on task/04-arrays-tasks.js
> +      : 0
In this case, it can also return 0. Which means the condition can be removed. In general, originally, I was thinking of adding a condition to avoid calling functions and return the value immediately if the length is zero

2023-08-22 08:35 UTC, juliaakor commented on task/04-arrays-tasks.js
> +      const numbersOrder = ['zero', 'one', 'two', 'three', 'four','five', 'six', 'seven', 'eight', 'nine']
So in similar cases, we should keep in mind the time complexity of the collection to be selected and choose the most optimal methods if possible?

2023-08-22 08:36 UTC, juliaakor commented on task/04-arrays-tasks.js
> +   , 0)
Yes, I have used a similar solution before with filter and applying the length property. So in this case of choosing between these two solutions filter looks cleaner and we don't need to work with additional variables?

2023-08-22 08:37 UTC, juliaakor commented on task/04-arrays-tasks.js
> +   return Array.from({length: end - start + 1},(value, index)=> start + index)
So the arguments we don't need can always be left as _? Originally, I wanted to come up with a solution without using unused arguments, but the solution would have been more complicated

2023-08-22 10:32 UTC, paperstick commented on task/04-arrays-tasks.js
> +      : 0
`filter` method won't call any function if the length of the array is 0

2023-08-22 10:34 UTC, paperstick commented on task/04-arrays-tasks.js
> +      const numbersOrder = ['zero', 'one', 'two', 'three', 'four','five', 'six', 'seven', 'eight', 'nine']
Well, it always good to find the solution in between optimal time complexity and code cleanliness

2023-08-22 10:37 UTC, paperstick commented on task/04-arrays-tasks.js
> +   , 0)
It depends on the situation, since `filter` returns a new array, which needs `O(n)` memory, where `n` is length of the result array. In this task we can afford creating a new array to get a bit more cleaner solution

2023-08-22 10:38 UTC, paperstick commented on task/04-arrays-tasks.js
> +   return Array.from({length: end - start + 1},(value, index)=> start + index)
Yep, you are right

2023-08-22 10:41 UTC, paperstick commented on task/04-arrays-tasks.js
> +            (element, elementIndex) => (rowIndex == elementIndex) ? 1 : 0
```suggestion
            (element, elementIndex) => Number(rowIndex == elementIndex)
```

2023-08-22 10:41 UTC, paperstick commented on task/04-arrays-tasks.js
> +
We don't need newlines before `return` in such cases. There are no other logical blocks inside the function which should be separated with `return` statement.

2023-08-22 10:41 UTC, paperstick commented on task/04-arrays-tasks.js
> +
The same here

2023-08-22 10:41 UTC, paperstick commented on task/04-arrays-tasks.js
> +      }, '')
Can you find a one-line solution using `join`?

2023-08-24 04:43 UTC, paperstick approved these changes

2023-08-24 05:06 UTC, merged